/**
 * Koydo Worlds — World Registry
 *
 * All 50 worlds, fully configured. Each world is a self-contained
 * Fabric (plugin) loaded by the Loom engine. The Great Archive (world 43)
 * is the hub — every child arrives here first.
 *
 * Color palettes, biomes, and Threadway connections are the canonical
 * source of truth for both the UE5 plugin and the Supabase seed.
 */

import type { WorldDefinition } from './types.js';

// ─── Realm of Discovery (STEM) — 15 worlds ─────────────────────────

const DISCOVERY_WORLDS: readonly WorldDefinition[] = [
  {
    id: 'cloud-kingdom',
    name: 'Cloud Kingdom',
    realm: 'discovery',
    subject: 'Earth Science / Weather',
    guideId: 'professor-nimbus',
    description:
      'A realm above the clouds where weather patterns write the sky. Barometric towers and storm-glass instruments track every pressure change.',
    colorPalette: {
      primary: '#5B8DB8',
      secondary: '#C9DCF0',
      accent: '#F5E642',
      fadedVariant: '#8C9DAD',
      restoredVariant: '#1A6EA8',
    },
    lightingMood: 'Overcast silver brightening to sunlit cerulean as luminance rises',
    biomeKit: 'cloudscape',
    entryIds: [
      'entry-barometer-torricelli',
      'entry-cloud-naming-howard',
      'entry-lightning-franklin',
      'entry-fitzroy-weather-forecast',
    ],
    threadwayConnections: ['great-archive', 'starfall-observatory'],
  },
  {
    id: 'savanna-workshop',
    name: 'Savanna Workshop',
    realm: 'discovery',
    subject: 'Engineering / Simple Machines',
    guideId: 'zara-ngozi',
    description:
      'An open-air workshop on the savanna. Zara\'s mechanical creations — levers, pulleys, gear trains — dot the landscape like iron-and-acacia sculptures.',
    colorPalette: {
      primary: '#C87941',
      secondary: '#F5D98B',
      accent: '#2D8A4E',
      fadedVariant: '#B09A80',
      restoredVariant: '#A85A1A',
    },
    lightingMood: 'Golden hour, always. The tools cast long warm shadows.',
    biomeKit: 'savanna',
    entryIds: [
      'entry-archimedes-lever',
      'entry-nok-iron-smelting',
      'entry-great-zimbabwe-walls',
      'entry-wright-brothers-workshop',
    ],
    threadwayConnections: ['great-archive', 'circuit-marsh'],
  },
  {
    id: 'tideline-bay',
    name: 'Tideline Bay',
    realm: 'discovery',
    subject: 'Ocean Science / Biology',
    guideId: 'suki-tanaka-reyes',
    description:
      'A tidal bay where the ocean and land negotiate. Tide pools reveal entire ecosystems. Suki\'s field sketches paper every available surface.',
    colorPalette: {
      primary: '#1A6B8A',
      secondary: '#7DC7D8',
      accent: '#FF8C42',
      fadedVariant: '#5C8A96',
      restoredVariant: '#0A4E6B',
    },
    lightingMood: 'Cool blue-green light, shafts of sun through shallow water',
    biomeKit: 'coastal',
    entryIds: [
      'entry-giant-squid-discovery',
      'entry-humpback-whale-migration',
      'entry-coral-spawning',
      'entry-coelacanth-living-fossil',
    ],
    threadwayConnections: ['great-archive', 'meadow-lab'],
  },
  {
    id: 'meadow-lab',
    name: 'The Meadow Lab',
    realm: 'discovery',
    subject: 'Plant Biology / Ecology',
    guideId: 'baxter',
    description:
      'Baxter\'s outdoor laboratory — beehives, microscopes in the grass, UV-spectrum lanterns that show flowers as bees see them.',
    colorPalette: {
      primary: '#4A8C3F',
      secondary: '#C2E88A',
      accent: '#FFD700',
      fadedVariant: '#7A9A74',
      restoredVariant: '#2A6C1F',
    },
    lightingMood: 'Warm spring afternoon, pollen haze in the air',
    biomeKit: 'temperate_meadow',
    entryIds: [
      'entry-mendel-inheritance',
      'entry-maathai-green-belt',
      'entry-mycorrhizal-networks',
      'entry-colony-collapse',
    ],
    threadwayConnections: ['great-archive', 'tideline-bay', 'greenhouse-spiral'],
  },
  {
    id: 'starfall-observatory',
    name: 'Starfall Observatory',
    realm: 'discovery',
    subject: 'Space Science / Astronomy',
    guideId: 'riku-osei',
    description:
      'Built for darkness. Tactile star maps line the walls. Riku navigates by touch and sound. The telescope points at midnight permanently.',
    colorPalette: {
      primary: '#1A1440',
      secondary: '#6B5B95',
      accent: '#FFD700',
      fadedVariant: '#3A3460',
      restoredVariant: '#08093A',
    },
    lightingMood: 'Perpetual clear midnight, Milky Way at max visibility',
    biomeKit: 'mountain_peak',
    entryIds: [
      'entry-ibn-al-haytham-optics',
      'entry-galileo-jupiter-moons',
      'entry-henrietta-leavitt-cepheids',
      'entry-james-webb-telescope',
    ],
    threadwayConnections: ['great-archive', 'cloud-kingdom'],
  },
  {
    id: 'number-garden',
    name: 'The Number Garden',
    realm: 'discovery',
    subject: 'Mathematics / Patterns',
    guideId: 'dottie-chakravarti',
    description:
      'Fibonacci spirals in the flower beds. Fractal ferns. Dottie\'s sari prints are geometric designs she calculated herself.',
    colorPalette: {
      primary: '#2E7D32',
      secondary: '#A5D6A7',
      accent: '#FF8F00',
      fadedVariant: '#5A7A5C',
      restoredVariant: '#1B5E20',
    },
    lightingMood: 'Warm afternoon garden light, mathematical golden ratio in every shadow',
    biomeKit: 'formal_garden',
    entryIds: [
      'entry-fibonacci-rabbit-problem',
      'entry-zero-invention',
      'entry-hypatia-alexandria',
      'entry-ada-lovelace-program',
    ],
    threadwayConnections: ['great-archive', 'calculation-caves', 'music-meadow'],
  },
  {
    id: 'calculation-caves',
    name: 'The Calculation Caves',
    realm: 'discovery',
    subject: 'Arithmetic / Mental Math',
    guideId: 'cal',
    description:
      'Crystal caverns where Cal pulses with each operation. Blue for addition, amber for subtraction. The walls display every calculation ever made here.',
    colorPalette: {
      primary: '#37474F',
      secondary: '#90CAF9',
      accent: '#FFB300',
      fadedVariant: '#607D8B',
      restoredVariant: '#1C313A',
    },
    lightingMood: 'Crystalline bioluminescence — color changes with the current operation',
    biomeKit: 'crystal_cave',
    entryIds: [
      'entry-ishango-bone',
      'entry-al-khwarizmi-algebra',
      'entry-babylonian-base60',
      'entry-goldbach-conjecture',
    ],
    threadwayConnections: ['great-archive', 'number-garden'],
  },
  {
    id: 'magnet-hills',
    name: 'The Magnet Hills',
    realm: 'discovery',
    subject: 'Physics / Forces & Motion',
    guideId: 'lena-sundstrom',
    description:
      'Rolling hills where magnetic fields are visible as shimmering lines. Lena\'s throwing circles are worn into the hilltops from decades of demonstrations.',
    colorPalette: {
      primary: '#4527A0',
      secondary: '#B39DDB',
      accent: '#E65100',
      fadedVariant: '#7E57C2',
      restoredVariant: '#311B92',
    },
    lightingMood: 'Dynamic — aurora-like waves of magnetic field light',
    biomeKit: 'rolling_hills',
    entryIds: [
      'entry-newton-laws-of-motion',
      'entry-curie-radioactivity',
      'entry-romer-speed-of-light',
      'entry-foucault-pendulum',
    ],
    threadwayConnections: ['great-archive', 'circuit-marsh'],
  },
  {
    id: 'circuit-marsh',
    name: 'The Circuit Marsh',
    realm: 'discovery',
    subject: 'Electricity / Circuits',
    guideId: 'kofi-amponsah',
    description:
      'Circuits built from swamp reeds and copper wire. Kofi\'s solar grid powers the whole marsh. The fireflies are actually LEDs he built at age 16.',
    colorPalette: {
      primary: '#1B5E20',
      secondary: '#A5D6A7',
      accent: '#FF6F00',
      fadedVariant: '#4E6E50',
      restoredVariant: '#003300',
    },
    lightingMood: 'Dusk over marshland, warm circuits glowing amber in the reeds',
    biomeKit: 'wetland',
    entryIds: [
      'entry-franklin-kite',
      'entry-volta-battery',
      'entry-edison-latimer-lightbulb',
      'entry-solar-panel',
    ],
    threadwayConnections: ['great-archive', 'savanna-workshop', 'magnet-hills'],
  },
  {
    id: 'code-canyon',
    name: 'Code Canyon',
    realm: 'discovery',
    subject: 'Coding / Logic',
    guideId: 'pixel',
    description:
      'A canyon where Pixel flickers between physical and digital. Code blocks are physical objects you can stack. Every build here makes something real.',
    colorPalette: {
      primary: '#006064',
      secondary: '#80DEEA',
      accent: '#FF4081',
      fadedVariant: '#37747A',
      restoredVariant: '#003A40',
    },
    lightingMood: 'Clean digital blue-white with neon accents',
    biomeKit: 'digital_scape',
    entryIds: [
      'entry-hamilton-apollo-software',
      'entry-spacewar-first-game',
      'entry-eniac-programmers',
      'entry-y2k-bug',
    ],
    threadwayConnections: ['great-archive', 'data-stream'],
  },
  {
    id: 'body-atlas',
    name: 'The Body Atlas',
    realm: 'discovery',
    subject: 'Human Body / Health Science',
    guideId: 'dr-emeka-obi',
    description:
      'Dr. Obi\'s holographic anatomy displays fill the air. Walking paths trace the circulatory system at human scale.',
    colorPalette: {
      primary: '#880E4F',
      secondary: '#F48FB1',
      accent: '#E65100',
      fadedVariant: '#9E4E6F',
      restoredVariant: '#560027',
    },
    lightingMood: 'Clean medical white with warm specimen lighting',
    biomeKit: 'indoor_museum',
    entryIds: [
      'entry-harvey-blood-circulation',
      'entry-jenner-first-vaccine',
      'entry-franklin-photo51-dna',
      'entry-human-microbiome',
    ],
    threadwayConnections: ['great-archive', 'wellness-garden'],
  },
  {
    id: 'frost-peaks',
    name: 'The Frost Peaks',
    realm: 'discovery',
    subject: 'Geology / Rocks & Minerals',
    guideId: 'mira-petrov',
    description:
      'Mountain peaks where rock layers tell 4 billion years of Earth\'s story. Mira reads the strata like pages.',
    colorPalette: {
      primary: '#37474F',
      secondary: '#CFD8DC',
      accent: '#00BCD4',
      fadedVariant: '#607D8B',
      restoredVariant: '#1C313A',
    },
    lightingMood: 'Vast, ancient — thin alpine light, deep shadows in the rock faces',
    biomeKit: 'alpine',
    entryIds: [
      'entry-mary-anning',
      'entry-wegener-continental-drift',
      'entry-ice-cores-climate',
      'entry-ring-of-fire',
    ],
    threadwayConnections: ['great-archive', 'map-room'],
  },
  {
    id: 'greenhouse-spiral',
    name: 'The Greenhouse Spiral',
    realm: 'discovery',
    subject: 'Chemistry / Mixtures & Materials',
    guideId: 'hugo-fontaine',
    description:
      'Hugo\'s spiral greenhouse where every experiment grows something. The three seeds he carried from Haiti are the oldest plants here.',
    colorPalette: {
      primary: '#1A6B3A',
      secondary: '#B2DFDB',
      accent: '#FF8A65',
      fadedVariant: '#4E7A60',
      restoredVariant: '#004D20',
    },
    lightingMood: 'Warm greenhouse afternoon, steam from chemical reactions',
    biomeKit: 'greenhouse',
    entryIds: [
      'entry-mendeleev-periodic-table',
      'entry-lavoisier-chemistry-revolution',
      'entry-discovery-of-oxygen',
      'entry-photosynthesis',
    ],
    threadwayConnections: ['great-archive', 'meadow-lab'],
  },
  {
    id: 'data-stream',
    name: 'The Data Stream',
    realm: 'discovery',
    subject: 'Data Science / Sorting & Graphing',
    guideId: 'yuki',
    description:
      'A world that makes complete sense: everything is categorized, every pattern visible. Yuki\'s charts fill the landscape like stained glass windows.',
    colorPalette: {
      primary: '#0D47A1',
      secondary: '#BBDEFB',
      accent: '#F57F17',
      fadedVariant: '#3A5E8A',
      restoredVariant: '#0A2D70',
    },
    lightingMood: 'Cool analytical blue. Data flows like rivers.',
    biomeKit: 'data_landscape',
    entryIds: [
      'entry-nightingale-rose-chart',
      'entry-snow-cholera-map',
      'entry-rosling-bubble-chart',
      'entry-misinformation-epidemic',
    ],
    threadwayConnections: ['great-archive', 'code-canyon'],
  },
  {
    id: 'map-room',
    name: 'The Map Room',
    realm: 'discovery',
    subject: 'Geography / Maps & Navigation',
    guideId: 'atlas',
    description:
      'Atlas stands at the center, his stone body mapped with glowing pathways. He cannot leave, but knows every route across every terrain.',
    colorPalette: {
      primary: '#4E342E',
      secondary: '#D7CCC8',
      accent: '#FDD835',
      fadedVariant: '#7A5E5A',
      restoredVariant: '#2C1A17',
    },
    lightingMood: 'Warm cartographers\' lamp, parchment tones',
    biomeKit: 'library_hall',
    entryIds: [
      'entry-polynesian-navigators',
      'entry-mercator-projection',
      'entry-prime-meridian',
      'entry-gps-democratisation',
    ],
    threadwayConnections: ['great-archive', 'frost-peaks', 'time-gallery'],
  },
];

// ─── Realm of Expression (Language Arts) — 15 worlds ────────────────

const EXPRESSION_WORLDS: readonly WorldDefinition[] = [
  {
    id: 'story-tree',
    name: 'The Story Tree',
    realm: 'expression',
    subject: 'Storytelling / Narrative',
    guideId: 'grandmother-anaya',
    description:
      'An ancient tree whose branches hold glowing story-orbs. Each orb is a story someone remembered here. Grandmother Anaya never reads from books.',
    colorPalette: {
      primary: '#8D6E63',
      secondary: '#FFD180',
      accent: '#558B2F',
      fadedVariant: '#A08070',
      restoredVariant: '#5D4037',
    },
    lightingMood: 'Firelight warmth, evening glow, stories told around embers',
    biomeKit: 'ancient_forest',
    entryIds: [
      'entry-gilgamesh',
      'entry-scheherazade',
      'entry-gutenberg-press',
      'entry-rosetta-stone',
    ],
    threadwayConnections: ['great-archive', 'diary-lighthouse', 'folklore-bazaar'],
  },
  {
    id: 'rhyme-docks',
    name: 'The Rhyme Docks',
    realm: 'expression',
    subject: 'Poetry / Rhyme & Rhythm',
    guideId: 'felix-barbosa',
    description:
      'Working harbor where Felix recites poetry between cargo sorties. Sonnets tattooed on his arms catch the dock light.',
    colorPalette: {
      primary: '#16213E',
      secondary: '#6B8FA9',
      accent: '#F5A623',
      fadedVariant: '#3D5468',
      restoredVariant: '#0A1128',
    },
    lightingMood: 'Salt-mist morning, rope coils and gulls, golden dock light',
    biomeKit: 'harbor',
    entryIds: [
      'entry-homer-iliad',
      'entry-phillis-wheatley',
      'entry-haiku-basho',
      'entry-langston-hughes-blues',
    ],
    threadwayConnections: ['great-archive', 'story-tree'],
  },
  {
    id: 'letter-forge',
    name: 'The Letter Forge',
    realm: 'expression',
    subject: 'Phonics / Letter Recognition',
    guideId: 'amara-diallo',
    description:
      'Amara forges letters from clay, metal, and light. Each character is a sculpture. She speaks four languages, reads all of them with her lips moving.',
    colorPalette: {
      primary: '#BF360C',
      secondary: '#FFCCBC',
      accent: '#33691E',
      fadedVariant: '#9E6F5A',
      restoredVariant: '#7F2600',
    },
    lightingMood: 'Forge fire, glowing letterforms cooling on the workbench',
    biomeKit: 'artisan_workshop',
    entryIds: [
      'entry-cuneiform-clay',
      'entry-phoenician-alphabet',
      'entry-braille-invention',
      'entry-champollion-hieroglyphs',
    ],
    threadwayConnections: ['great-archive', 'spelling-mines'],
  },
  {
    id: 'reading-reef',
    name: 'The Reading Reef',
    realm: 'expression',
    subject: 'Reading Comprehension',
    guideId: 'oliver-marsh',
    description:
      'Oliver\'s library is embedded in living coral. He reads by touch and audio. "Comprehension is understanding — not seeing."',
    colorPalette: {
      primary: '#01579B',
      secondary: '#B3E5FC',
      accent: '#FF6D00',
      fadedVariant: '#3D759E',
      restoredVariant: '#003070',
    },
    lightingMood: 'Dappled undersea light, filtered blue-green, coral bioluminescence',
    biomeKit: 'coral_reef',
    entryIds: [
      'entry-silent-reading',
      'entry-braille-underwater-library',
      'entry-public-library',
      'entry-speed-reading-limits',
    ],
    threadwayConnections: ['great-archive', 'nonfiction-fleet'],
  },
  {
    id: 'grammar-bridge',
    name: 'The Grammar Bridge',
    realm: 'expression',
    subject: 'Grammar / Sentence Structure',
    guideId: 'lila-johansson-park',
    description:
      'Lila builds sentences like bridges — load-bearing nouns, connecting verbs. Every grammatical error is a structural flaw waiting to collapse.',
    colorPalette: {
      primary: '#4A148C',
      secondary: '#CE93D8',
      accent: '#F57F17',
      fadedVariant: '#7A50AA',
      restoredVariant: '#270057',
    },
    lightingMood: 'Engineering precision — clean architect\'s light over blueprints',
    biomeKit: 'bridge_district',
    entryIds: [
      'entry-panini-first-grammar',
      'entry-chomsky-universal-grammar',
      'entry-great-vowel-shift',
      'entry-sign-language-grammar',
    ],
    threadwayConnections: ['great-archive', 'editing-tower'],
  },
  {
    id: 'vocabulary-jungle',
    name: 'The Vocabulary Jungle',
    realm: 'expression',
    subject: 'Vocabulary / Word Roots',
    guideId: 'kwame-asante',
    description:
      'Kwame\'s jungle where words grow like vines — Latin roots at the base, English branches above, meanings fruiting at the tips.',
    colorPalette: {
      primary: '#1B5E20',
      secondary: '#A5D6A7',
      accent: '#F9A825',
      fadedVariant: '#4E7252',
      restoredVariant: '#003300',
    },
    lightingMood: 'Dense tropical canopy, word-light filtering through leaves',
    biomeKit: 'jungle',
    entryIds: [
      'entry-oxford-english-dictionary',
      'entry-shakespeare-invented-words',
      'entry-loanwords-norman-conquest',
      'entry-how-words-enter-dictionary',
    ],
    threadwayConnections: ['great-archive', 'translation-garden'],
  },
  {
    id: 'punctuation-station',
    name: 'The Punctuation Station',
    realm: 'expression',
    subject: 'Punctuation / Writing Mechanics',
    guideId: 'rosie-chen',
    description:
      'An old railway station where every sign is punctuated precisely. Missing commas cause trains to miss stops. Periods stop everything.',
    colorPalette: {
      primary: '#E65100',
      secondary: '#FFE0B2',
      accent: '#1A237E',
      fadedVariant: '#A07050',
      restoredVariant: '#BF3600',
    },
    lightingMood: 'Warm station amber, steam, mechanical precision',
    biomeKit: 'train_station',
    entryIds: [
      'entry-aristophanes-punctuation',
      'entry-gutenberg-standardised-punctuation',
      'entry-aldus-manutius-semicolon',
      'entry-interrobang-invention',
    ],
    threadwayConnections: ['great-archive', 'grammar-bridge'],
  },
  {
    id: 'debate-arena',
    name: 'The Debate Arena',
    realm: 'expression',
    subject: 'Persuasive Writing',
    guideId: 'theo-papadopoulos',
    description:
      'An amphitheater where every argument is a structure: claim, evidence, reasoning. Theo has never won without evidence.',
    colorPalette: {
      primary: '#263238',
      secondary: '#90A4AE',
      accent: '#FF5722',
      fadedVariant: '#546E7A',
      restoredVariant: '#102027',
    },
    lightingMood: 'Dramatic arena lighting — spotlit podiums, dark audience',
    biomeKit: 'amphitheater',
    entryIds: [
      'entry-aristotle-persuasion',
      'entry-lincoln-douglas-debates',
      'entry-logical-fallacies',
      'entry-malala-un-speech',
    ],
    threadwayConnections: ['great-archive', 'thinking-grove'],
  },
  {
    id: 'diary-lighthouse',
    name: 'The Diary Lighthouse',
    realm: 'expression',
    subject: 'Creative Writing / Journaling',
    guideId: 'nadia-volkov',
    description:
      'Nadia\'s lighthouse keeps her thoughts safe. She\'ll let you read one page, maybe. The light it casts writes shadows on the wall.',
    colorPalette: {
      primary: '#37474F',
      secondary: '#B0BEC5',
      accent: '#FF8A65',
      fadedVariant: '#607D8B',
      restoredVariant: '#1C313A',
    },
    lightingMood: 'Moody coastal night, lighthouse beam sweeping warm light',
    biomeKit: 'coastal_lighthouse',
    entryIds: [
      'entry-anne-frank-diary',
      'entry-pepys-diary',
      'entry-sei-shonagon-pillow-book',
      'entry-frida-kahlo-diary',
    ],
    threadwayConnections: ['great-archive', 'story-tree'],
  },
  {
    id: 'spelling-mines',
    name: 'The Spelling Mines',
    realm: 'expression',
    subject: 'Spelling / Word Patterns',
    guideId: 'benny-okafor-williams',
    description:
      'Benny mines words from the rock face. Unusual spellings are gemstones. Phonetic patterns are visible as vein structures in the cave walls.',
    colorPalette: {
      primary: '#4E342E',
      secondary: '#BCAAA4',
      accent: '#7CB342',
      fadedVariant: '#7A6058',
      restoredVariant: '#2C1A17',
    },
    lightingMood: 'Lantern-lit mine tunnels, gemstone glitter',
    biomeKit: 'mine_shaft',
    entryIds: [
      'entry-noah-webster-dictionary',
      'entry-norman-conquest-spelling',
      'entry-scripps-spelling-bee',
      'entry-ipa-phonetic-alphabet',
    ],
    threadwayConnections: ['great-archive', 'letter-forge'],
  },
  {
    id: 'translation-garden',
    name: 'The Translation Garden',
    realm: 'expression',
    subject: 'Multilingual Awareness',
    guideId: 'farah-al-rashid',
    description:
      'Farah\'s garden where the same flower has 40 names — one per language she speaks. Each name tag shows the script and the sound.',
    colorPalette: {
      primary: '#00695C',
      secondary: '#B2DFDB',
      accent: '#FF8F00',
      fadedVariant: '#4A8A80',
      restoredVariant: '#003D30',
    },
    lightingMood: 'Midday garden light, texts from many cultures floating like leaves',
    biomeKit: 'formal_garden',
    entryIds: [
      'entry-house-of-wisdom',
      'entry-septuagint-translation',
      'entry-nuremberg-interpretation',
      'entry-google-translate',
    ],
    threadwayConnections: ['great-archive', 'vocabulary-jungle'],
  },
  {
    id: 'nonfiction-fleet',
    name: 'The Nonfiction Fleet',
    realm: 'expression',
    subject: 'Research Skills / Nonfiction Reading',
    guideId: 'captain-birch',
    description:
      'Captain Birch\'s research fleet — each ship is an information source. Primary sources at port, secondary in the harbor, tertiary at sea.',
    colorPalette: {
      primary: '#1A237E',
      secondary: '#9FA8DA',
      accent: '#FF6D00',
      fadedVariant: '#3A4A7E',
      restoredVariant: '#0D1250',
    },
    lightingMood: 'Open sea daylight, spray and sails, navigational clarity',
    biomeKit: 'harbor',
    entryIds: [
      'entry-pliny-natural-history',
      'entry-wollstonecraft-vindication',
      'entry-encyclopedie',
      'entry-rachel-carson-silent-spring',
    ],
    threadwayConnections: ['great-archive', 'reading-reef'],
  },
  {
    id: 'illustration-cove',
    name: 'The Illustration Cove',
    realm: 'expression',
    subject: 'Visual Literacy',
    guideId: 'ines-moreau',
    description:
      'Ines communicates through drawings, always has. Her cove is covered in illustrated stories — wordless narratives on every surface.',
    colorPalette: {
      primary: '#880E4F',
      secondary: '#F8BBD0',
      accent: '#33691E',
      fadedVariant: '#9E5A70',
      restoredVariant: '#560027',
    },
    lightingMood: 'Studio north light — even, warm, perfect for color accuracy',
    biomeKit: 'coastal_cave',
    entryIds: [
      'entry-lascaux-cave-paintings',
      'entry-bayeux-tapestry',
      'entry-hokusai-great-wave',
      'entry-beatrix-potter',
    ],
    threadwayConnections: ['great-archive', 'story-tree'],
  },
  {
    id: 'folklore-bazaar',
    name: 'The Folklore Bazaar',
    realm: 'expression',
    subject: 'Folklore / Cultural Stories',
    guideId: 'hassan-yilmaz',
    description:
      'Hassan\'s bazaar where every stall sells a story from a different culture. The Anansi booth is next to the Baba Yaga booth. They get along.',
    colorPalette: {
      primary: '#BF360C',
      secondary: '#FFCCBC',
      accent: '#1B5E20',
      fadedVariant: '#9E5A40',
      restoredVariant: '#7F2600',
    },
    lightingMood: 'Festival color, warm evening market lights, lanterns and fires',
    biomeKit: 'open_bazaar',
    entryIds: [
      'entry-brothers-grimm',
      'entry-anansi-stories',
      'entry-one-thousand-one-nights',
      'entry-aboriginal-dreamtime',
    ],
    threadwayConnections: ['great-archive', 'story-tree', 'translation-garden'],
  },
  {
    id: 'editing-tower',
    name: 'The Editing Tower',
    realm: 'expression',
    subject: 'Editing / Revision',
    guideId: 'wren-calloway',
    description:
      'Wren\'s tower where every floor is a revision pass. The ground floor is raw draft. The top floor is the final, clean version.',
    colorPalette: {
      primary: '#4A235A',
      secondary: '#CE93D8',
      accent: '#F57F17',
      fadedVariant: '#7A507A',
      restoredVariant: '#2A0A3A',
    },
    lightingMood: 'Quiet editorial afternoon — window light on a desk of manuscripts',
    biomeKit: 'tower_study',
    entryIds: [
      'entry-maxwell-perkins',
      'entry-hemingway-iceberg-theory',
      'entry-toni-morrison-revision',
      'entry-wikipedia-editing',
    ],
    threadwayConnections: ['great-archive', 'grammar-bridge', 'diary-lighthouse'],
  },
];

// ─── Realm of Exchange (Financial Literacy) — 12 worlds ─────────────

const EXCHANGE_WORLDS: readonly WorldDefinition[] = [
  {
    id: 'market-square',
    name: 'The Market Square',
    realm: 'exchange',
    subject: 'Money Basics / Trade',
    guideId: 'tia-carmen-herrera',
    description:
      'Tía Carmen\'s bustling square where everything has a price and every trade requires fairness. Steel drums playing. Mango stalls and ceramics.',
    colorPalette: {
      primary: '#BF360C',
      secondary: '#FFCCBC',
      accent: '#1A6B3A',
      fadedVariant: '#9E6050',
      restoredVariant: '#7F2600',
    },
    lightingMood: 'Midday market sun, warm terracotta shadows, vibrant trade activity',
    biomeKit: 'open_market',
    entryIds: [
      'entry-lydian-coin',
      'entry-silk-road',
      'entry-double-entry-bookkeeping',
      'entry-first-paper-money',
    ],
    threadwayConnections: ['great-archive', 'barter-docks', 'savings-vault'],
  },
  {
    id: 'savings-vault',
    name: 'The Savings Vault',
    realm: 'exchange',
    subject: 'Saving / Compound Interest',
    guideId: 'mr-abernathy',
    description:
      'Mr. Abernathy\'s vault where coins grow visibly over time. Compound interest is demonstrated with actual glowing piles that multiply while you watch.',
    colorPalette: {
      primary: '#1A237E',
      secondary: '#C5CAE9',
      accent: '#F9A825',
      fadedVariant: '#3A4A7E',
      restoredVariant: '#0D1250',
    },
    lightingMood: 'Rich bank vault amber — polished brass and stacked coin towers',
    biomeKit: 'vault_interior',
    entryIds: [
      'entry-piggy-bank-history',
      'entry-bank-of-amsterdam',
      'entry-compound-interest',
      'entry-freedmans-bank',
    ],
    threadwayConnections: ['great-archive', 'market-square', 'investment-greenhouse'],
  },
  {
    id: 'budget-kitchen',
    name: 'The Budget Kitchen',
    realm: 'exchange',
    subject: 'Budgeting / Resource Allocation',
    guideId: 'priya-nair',
    description:
      'Priya\'s kitchen where every ingredient has a cost and every meal must fit the week\'s budget. Real math on real resources.',
    colorPalette: {
      primary: '#E65100',
      secondary: '#FFE0B2',
      accent: '#2E7D32',
      fadedVariant: '#A07050',
      restoredVariant: '#BF3600',
    },
    lightingMood: 'Warm kitchen afternoon light, organized shelves, chalkboard budgets',
    biomeKit: 'domestic_kitchen',
    entryIds: [
      'entry-ration-book',
      'entry-yunus-microfinance',
      'entry-opportunity-cost',
      'entry-spice-trade-kitchens',
    ],
    threadwayConnections: ['great-archive', 'market-square', 'needs-wants-bridge'],
  },
  {
    id: 'entrepreneur-workshop',
    name: "The Entrepreneur's Workshop",
    realm: 'exchange',
    subject: 'Entrepreneurship',
    guideId: 'diego-montoya-silva',
    description:
      'Diego built his first business from a cart. The workshop walls show every business he\'s started — what worked, what failed, what he learned.',
    colorPalette: {
      primary: '#4A235A',
      secondary: '#CE93D8',
      accent: '#FF8F00',
      fadedVariant: '#7A507A',
      restoredVariant: '#2A0A3A',
    },
    lightingMood: 'Startup energy — bright workshop light, prototypes everywhere',
    biomeKit: 'workshop',
    entryIds: ['entry-madam-cj-walker', 'entry-failure-wall', 'entry-the-pivot', 'entry-patent-law'],
    threadwayConnections: ['great-archive', 'job-fair', 'market-square'],
  },
  {
    id: 'sharing-meadow',
    name: 'The Sharing Meadow',
    realm: 'exchange',
    subject: 'Giving / Community Economics',
    guideId: 'auntie-bee',
    description:
      'Auntie Bee\'s meadow: the more you give away, the fuller the meadow gets. Community economics through the lens of generosity.',
    colorPalette: {
      primary: '#2E7D32',
      secondary: '#A5D6A7',
      accent: '#FF8F00',
      fadedVariant: '#5A7A5C',
      restoredVariant: '#1B5E20',
    },
    lightingMood: 'Community picnic light — warm, open, abundant',
    biomeKit: 'temperate_meadow',
    entryIds: ['entry-the-commons', 'entry-gift-economy', 'entry-cooperative-movement', 'entry-open-source'],
    threadwayConnections: ['great-archive', 'charity-harbor', 'needs-wants-bridge'],
  },
  {
    id: 'investment-greenhouse',
    name: 'The Investment Greenhouse',
    realm: 'exchange',
    subject: 'Investing / Risk & Reward',
    guideId: 'jin-ho-park',
    description:
      'Jin-ho\'s greenhouse where seeds are investments. Plant one today, wait, tend carefully — some fail, some flourish beyond expectation.',
    colorPalette: {
      primary: '#1A6B3A',
      secondary: '#B2DFDB',
      accent: '#FF8A65',
      fadedVariant: '#4E7A60',
      restoredVariant: '#004D20',
    },
    lightingMood: 'Long-exposure greenhouse — showing growth over time as light',
    biomeKit: 'greenhouse',
    entryIds: ['entry-warren-buffett', 'entry-invention-of-insurance', 'entry-zimbabwe-hyperinflation', 'entry-index-funds'],
    threadwayConnections: ['great-archive', 'savings-vault', 'debt-glacier'],
  },
  {
    id: 'needs-wants-bridge',
    name: 'The Needs & Wants Bridge',
    realm: 'exchange',
    subject: 'Smart Spending / Needs vs Wants',
    guideId: 'nia-oduya',
    description:
      'Nia\'s bridge where every crossing requires a decision: is this a need or a want? The bridge only lets you cross with clear thinking.',
    colorPalette: {
      primary: '#0D47A1',
      secondary: '#BBDEFB',
      accent: '#FF8F00',
      fadedVariant: '#3A5E8A',
      restoredVariant: '#0A2D70',
    },
    lightingMood: 'Clear decision-making light — clean, logical, no shadows to hide in',
    biomeKit: 'bridge_district',
    entryIds: ['entry-maslows-hierarchy', 'entry-planned-obsolescence', 'entry-diderot-effect', 'entry-hedonic-treadmill'],
    threadwayConnections: ['great-archive', 'budget-kitchen', 'sharing-meadow'],
  },
  {
    id: 'barter-docks',
    name: 'The Barter Docks',
    realm: 'exchange',
    subject: 'History of Money',
    guideId: 'tomas-reyes',
    description:
      'Tomás\'s docks where every trade era is docked like a ship: barter crates, first coins, paper notes, digital tokens.',
    colorPalette: {
      primary: '#4E342E',
      secondary: '#D7CCC8',
      accent: '#FDD835',
      fadedVariant: '#7A6058',
      restoredVariant: '#2C1A17',
    },
    lightingMood: 'Historic port amber — different lighting per dock era',
    biomeKit: 'harbor',
    entryIds: ['entry-double-coincidence', 'entry-yapese-rai-stones', 'entry-trans-saharan-salt-trade', 'entry-barter-modern-crises'],
    threadwayConnections: ['great-archive', 'market-square'],
  },
  {
    id: 'debt-glacier',
    name: 'The Debt Glacier',
    realm: 'exchange',
    subject: 'Borrowing / Debt Management',
    guideId: 'elsa-lindgren',
    description:
      'Elsa\'s glacier where debt is literally weight — borrow wrongly and it accumulates like ice. The path forward is always visible but requires careful navigation.',
    colorPalette: {
      primary: '#0D47A1',
      secondary: '#B3E5FC',
      accent: '#FF8F00',
      fadedVariant: '#3D6E8A',
      restoredVariant: '#0A2D70',
    },
    lightingMood: 'Cold arctic blue — vast, slow, consequential',
    biomeKit: 'glacier',
    entryIds: ['entry-concept-of-interest', 'entry-credit-score', 'entry-2008-financial-crisis', 'entry-student-debt'],
    threadwayConnections: ['great-archive', 'investment-greenhouse'],
  },
  {
    id: 'job-fair',
    name: 'The Job Fair',
    realm: 'exchange',
    subject: 'Earning / Careers',
    guideId: 'babatunde-afolabi',
    description:
      'Babatunde\'s fair where careers are explored not chosen. Every booth is a different world of work. Skills, not titles.',
    colorPalette: {
      primary: '#1A237E',
      secondary: '#9FA8DA',
      accent: '#FF8F00',
      fadedVariant: '#3A4A7E',
      restoredVariant: '#0D1250',
    },
    lightingMood: 'Optimistic career fair daylight — possibility everywhere',
    biomeKit: 'exhibition_hall',
    entryIds: ['entry-adam-smith-pin-factory', 'entry-child-labour-laws', 'entry-gig-economy', 'entry-equal-pay'],
    threadwayConnections: ['great-archive', 'entrepreneur-workshop'],
  },
  {
    id: 'charity-harbor',
    name: 'The Charity Harbor',
    realm: 'exchange',
    subject: 'Charitable Giving',
    guideId: 'mei-lin-wu',
    description:
      'Mei-Lin\'s harbor where ships arrive from communities that need help and leave with what they were brought. Giving has an address here.',
    colorPalette: {
      primary: '#006064',
      secondary: '#80DEEA',
      accent: '#FF8F00',
      fadedVariant: '#37747A',
      restoredVariant: '#003A40',
    },
    lightingMood: 'Warm harbor dawn — hope and purpose in every ship departure',
    biomeKit: 'harbor',
    entryIds: ['entry-effective-altruism', 'entry-red-cross-geneva', 'entry-carnegie-gospel-of-wealth', 'entry-zakat'],
    threadwayConnections: ['great-archive', 'sharing-meadow'],
  },
  {
    id: 'tax-office',
    name: 'The Tax Office',
    realm: 'exchange',
    subject: 'Taxes / Public Services',
    guideId: 'sam-worthington',
    description:
      'Sam demystifies taxes: every coin becomes something visible — a road, a school, a fire station. Public money, public purpose.',
    colorPalette: {
      primary: '#263238',
      secondary: '#90A4AE',
      accent: '#FDD835',
      fadedVariant: '#546E7A',
      restoredVariant: '#102027',
    },
    lightingMood: 'Civic building daylight — transparent, accountable, functional',
    biomeKit: 'civic_building',
    entryIds: ['entry-why-taxes-exist', 'entry-progressive-vs-flat-tax', 'entry-boston-tea-party', 'entry-how-countries-spend-taxes'],
    threadwayConnections: ['great-archive', 'budget-kitchen'],
  },
];

// ─── The Crossroads (Hub + Cross-Disciplinary) — 8 worlds ────────────

const CROSSROADS_WORLDS: readonly WorldDefinition[] = [
  {
    id: 'great-archive',
    name: 'The Great Archive',
    realm: 'crossroads',
    subject: 'Research & Inquiry',
    guideId: 'the-librarian',
    description:
      'The hub of all worlds. A vast, dimly lit library where The Librarian explains the Fading. Three Threadway portals glow faintly: STEM, Language, Finance.',
    colorPalette: {
      primary: '#4E342E',
      secondary: '#D7CCC8',
      accent: '#FDD835',
      fadedVariant: '#7A6058',
      restoredVariant: '#2C1A17',
    },
    lightingMood: 'Dusty archive amber, shaft of light, dust motes, ancient and welcoming',
    biomeKit: 'library_hall',
    entryIds: [
      'entry-great-library-alexandria',
      'entry-first-encyclopedia',
      'entry-internet-birth',
      'entry-wikipedia',
    ],
    threadwayConnections: [
      // Connected to all realm entry worlds
      'cloud-kingdom', 'savanna-workshop', 'tideline-bay', 'meadow-lab',
      'starfall-observatory', 'number-garden', 'calculation-caves', 'magnet-hills',
      'circuit-marsh', 'code-canyon', 'body-atlas', 'frost-peaks',
      'greenhouse-spiral', 'data-stream', 'map-room',
      'story-tree', 'rhyme-docks', 'letter-forge', 'reading-reef',
      'grammar-bridge', 'vocabulary-jungle', 'punctuation-station', 'debate-arena',
      'diary-lighthouse', 'spelling-mines', 'translation-garden', 'nonfiction-fleet',
      'illustration-cove', 'folklore-bazaar', 'editing-tower',
      'market-square', 'savings-vault', 'budget-kitchen', 'entrepreneur-workshop',
      'sharing-meadow', 'investment-greenhouse', 'needs-wants-bridge', 'barter-docks',
      'debt-glacier', 'job-fair', 'charity-harbor', 'tax-office',
      'workshop-crossroads', 'discovery-trail', 'thinking-grove',
      'wellness-garden', 'time-gallery', 'music-meadow', 'everywhere',
    ],
  },
  {
    id: 'workshop-crossroads',
    name: 'The Workshop Crossroads',
    realm: 'crossroads',
    subject: 'Design Thinking',
    guideId: 'kenzo-nakamura-osei',
    description:
      'Kenzo\'s crossroads workshop where problems from every world are brought and solved together. Design thinking is the language.',
    colorPalette: {
      primary: '#1A1440',
      secondary: '#CE93D8',
      accent: '#FF8A65',
      fadedVariant: '#403A65',
      restoredVariant: '#08093A',
    },
    lightingMood: 'Creative studio — warm incandescent inspiration',
    biomeKit: 'workshop',
    entryIds: [
      'entry-da-vinci-crossroads',
      'entry-bauhaus-art-industry',
      'entry-biomimicry',
      'entry-design-thinking-process',
    ],
    threadwayConnections: ['great-archive', 'discovery-trail'],
  },
  {
    id: 'discovery-trail',
    name: 'The Discovery Trail',
    realm: 'crossroads',
    subject: 'Scientific Method',
    guideId: 'solana-bright',
    description:
      'A trail through many terrains where Solana demonstrates: observe, question, hypothesize, test, conclude. Every biome is a fresh experiment.',
    colorPalette: {
      primary: '#1B5E20',
      secondary: '#C8E6C9',
      accent: '#FF8F00',
      fadedVariant: '#4E7252',
      restoredVariant: '#003300',
    },
    lightingMood: 'Expedition light — crisp morning, field of possibility',
    biomeKit: 'trail',
    entryIds: [
      'entry-scientific-method',
      'entry-citizen-science',
      'entry-failure-in-science',
      'entry-replication-crisis',
    ],
    threadwayConnections: ['great-archive', 'workshop-crossroads'],
  },
  {
    id: 'thinking-grove',
    name: 'The Thinking Grove',
    realm: 'crossroads',
    subject: 'Ethics / Critical Thinking',
    guideId: 'old-rowan',
    description:
      'Old Rowan has stood in this grove for centuries. He asks questions, never gives answers. The hardest questions grow where roots go deepest.',
    colorPalette: {
      primary: '#2E3B1E',
      secondary: '#A5C07A',
      accent: '#FF8F00',
      fadedVariant: '#5A6550',
      restoredVariant: '#1A2410',
    },
    lightingMood: 'Ancient forest dusk — philosophical light that asks questions',
    biomeKit: 'ancient_forest',
    entryIds: [
      'entry-ship-of-theseus',
      'entry-hammurabis-code',
      'entry-golden-rule-across-cultures',
      'entry-prisoners-dilemma',
    ],
    threadwayConnections: ['great-archive', 'debate-arena', 'time-gallery'],
  },
  {
    id: 'wellness-garden',
    name: 'The Wellness Garden',
    realm: 'crossroads',
    subject: 'Social-Emotional Learning',
    guideId: 'hana-bergstrom',
    description:
      'Hana\'s garden where emotions are named, understood, and tended like plants. Feelings that are named can be grown into something useful.',
    colorPalette: {
      primary: '#00695C',
      secondary: '#B2DFDB',
      accent: '#FF8F00',
      fadedVariant: '#4A8A80',
      restoredVariant: '#003D30',
    },
    lightingMood: 'Gentle healing warmth — the light here is always kind',
    biomeKit: 'zen_garden',
    entryIds: [
      'entry-science-of-sleep',
      'entry-power-of-play',
      'entry-growth-mindset',
      'entry-history-of-empathy',
    ],
    threadwayConnections: ['great-archive', 'body-atlas'],
  },
  {
    id: 'time-gallery',
    name: 'The Time Gallery',
    realm: 'crossroads',
    subject: 'Historical Thinking',
    guideId: 'rami-al-farsi',
    description:
      'Rami\'s gallery where history is not dates — it\'s cause and consequence. Every display shows the before, the after, and the reason.',
    colorPalette: {
      primary: '#37474F',
      secondary: '#B0BEC5',
      accent: '#FDD835',
      fadedVariant: '#607D8B',
      restoredVariant: '#1C313A',
    },
    lightingMood: 'Museum quality — each era has its own period lighting',
    biomeKit: 'museum_hall',
    entryIds: [
      'entry-invention-of-calendar',
      'entry-howard-zinn',
      'entry-oral-history',
      'entry-long-now-foundation',
    ],
    threadwayConnections: ['great-archive', 'thinking-grove', 'map-room'],
  },
  {
    id: 'music-meadow',
    name: 'The Music Meadow',
    realm: 'crossroads',
    subject: 'Music & Math Patterns',
    guideId: 'luna-esperanza',
    description:
      'Luna was nonverbal until age 4. Music gave her words. The meadow proves that rhythm is math, melody is pattern, harmony is physics.',
    colorPalette: {
      primary: '#6A1B9A',
      secondary: '#E1BEE7',
      accent: '#FFD700',
      fadedVariant: '#8A50A0',
      restoredVariant: '#4A0070',
    },
    lightingMood: 'Sunset concert — golden and purple, music made visible as light',
    biomeKit: 'outdoor_amphitheater',
    entryIds: [
      'entry-physics-of-sound',
      'entry-musical-notation',
      'entry-beethovens-deafness',
      'entry-the-blues',
    ],
    threadwayConnections: ['great-archive', 'number-garden'],
  },
  {
    id: 'everywhere',
    name: 'Everywhere',
    realm: 'crossroads',
    subject: 'Navigation / Tutorial',
    guideId: 'compass',
    description:
      'Compass is everywhere and nowhere. They appear as a warm glow beside every new Kindler, helping them find their first world.',
    colorPalette: {
      primary: '#FFFFFF',
      secondary: '#F5F5F5',
      accent: '#FFD700',
      fadedVariant: '#DDDDDD',
      restoredVariant: '#FFFFFF',
    },
    lightingMood: 'Warm tutorial glow — always welcoming, never overwhelming',
    biomeKit: 'everywhere',
    entryIds: [
      'entry-overview-effect',
      'entry-wayfinding',
      'entry-liminal-spaces',
      'entry-being-lost',
    ],
    threadwayConnections: ['great-archive'],
  },
];

// ─── World Registry ────────────────────────────────────────────────

export const WORLD_REGISTRY: ReadonlyMap<string, WorldDefinition> = new Map([
  ...DISCOVERY_WORLDS.map(w => [w.id, w] as const),
  ...EXPRESSION_WORLDS.map(w => [w.id, w] as const),
  ...EXCHANGE_WORLDS.map(w => [w.id, w] as const),
  ...CROSSROADS_WORLDS.map(w => [w.id, w] as const),
]);

export const ALL_WORLDS: readonly WorldDefinition[] = [
  ...DISCOVERY_WORLDS,
  ...EXPRESSION_WORLDS,
  ...EXCHANGE_WORLDS,
  ...CROSSROADS_WORLDS,
];

export function getWorld(id: string): WorldDefinition {
  const world = WORLD_REGISTRY.get(id);
  if (!world) throw new Error(`Unknown world: ${id}`);
  return world;
}

export function getWorldsByRealm(realm: WorldDefinition['realm']): readonly WorldDefinition[] {
  return ALL_WORLDS.filter(w => w.realm === realm);
}
